OZ-01-Team3/oz-main_project-be

apps/chat/admin.py
apps/chat/apps.py
apps/chat/consumers.py
apps/chat/models.py
apps/chat/routing.py
apps/chat/serializers.py
apps/chat/tests.py
apps/chat/urls.py
apps/chat/utils.py
apps/chat/views.py
apps/common/utils.py
config/asgi.py
config/settings/base.py
config/settings/local.py
config/urls.py
poetry.lock
pyproject.toml

- config/base.py
- CUSTOM_USER_APPS에 uvicorn, apps.chat 추가
- models.py
- 채팅방을 위한 Chatroom 모델 추가
- 채팅 메시지를 위한 Message 모델 추가
- 채팅방에 공지와 같은 알림을 위한 Alert 모델 추가
- upload_to_s3_chat 메서드 추가
-> 메시지로 보낸 이미지를 저장하기 위해 s3 경로를 설정해주는 메서드
- serializers.py
- MessageSerializer: 채팅 메시지 내용, 보낸이, 타임스탬프를 채팅방에 띄워주기 위해 사용
- CreateChatroomSerializer : 채팅방을 만들 때 필요한 데이터를 위해 필요한 시리얼라이저 
- test.py
- ChatRoomTestCase : 채팅방을 만들 때 생길 수 있는 예외, 오류, 정상적인 응답을 테스트
- ChatDetailTestCase : 채팅 메시지를 불러오거나 채팅방을 삭제할 때 생길 수 있는 예외, 오류, 정상적인 응답을 테스트
- urls.py
- api/chat/ : ChatRoomView, 채팅방 개설
- api/chat/<int:chatroom_id>/ : ChatDetailView, 채팅방 메시지 불러오기, 채팅방 나가기 및 삭제
- utils.py 
- check_entered_chatroom : 유저가 채팅방에 참여한 유저인지 확인하는 메서드
- change_entered_status : 요청을 보낸 유저의 상태 변환하는 메서드
- delete_chatroom : 둘다 채팅방을 나가면 채팅방을 삭제해주는 메서드
- 레디스를 …

[Feature/chat] uvicorn, channels 설정 및 chat 앱 초기 세팅, view 일부 작성

---

apps/product/admin.py
apps/product/models.py
apps/product/serializers.py
apps/product/urls.py
apps/product/views.py

Product
- rental history modelviewset 구현
- user를 lender로 변경
- 
-

[Feat: RentalHistory Model, ViewSet 구현]

---

apps/chat/consumers.py
apps/chat/routing.py
apps/chat/serializers.py
apps/chat/tests.py

- get_unread_chat_count: 읽지않은 채팅 수 내려줌
- 온라인 상태를 제대로 내려주는 지 테스트코드 추가
- 바뀐 Product 필드 명에따라 코드 수정
- 데이터 내려주는 부분 수정, on-offline 내려주는 부분 추가
- 
-

[Feature/chat consumers] 온라인상태 내려주기, 읽지않은 마지막 메시지, 읽지않은 메시지 수 내려주기 추가

---

apps/chat/admin.py
apps/chat/models.py
apps/chat/views.py
apps/notification/admin.py
apps/notification/models.py

- chat/admin.py
- MessageAdmin :
- 객체 생성
- 객체 수정
- 객체 삭제
- 읽음 상태 변환 가능(벌크 업데이트 사용)
- ChatroomAdmin:
- 객체 생성
- 객체 수정
- 객체 삭제
- 객체 리스트 조회 가능
- 대여자 또는 판매자의 채팅방 나가기 가능(벌크 업데이트)
- 인라인으로 채팅방 생성시 메시지 함께 생성가능
- notification/admin.py
- GlobalNotificationAdmin
- 객체 생성, 수정, 삭제, 조회 가능
- 인라인 기능으로 유저 컨펌 객체 함께 생성가능
- 모든 유저에게 메시지 보내기 기능 & 컨펌 객체 생성
- GlobalNotificationConfirmAdmin
- 객체 생성, 조회, 수정, 삭제 가능
- 선택한 컨펌 객체를 확인 상태로 변경가능
- RentalNotificationAdmin
- 객체 생성, 조회, 삭제, 수정 가능
- 선택한 알림 확인상태로 변경 가능
- GlobalNotification : 알림의 텍스트내용 30자가 보이게 수정
- Chatroom : 판매자 ,대여자의 닉네임이 보이도록 수정
- 
-

[Feature/admin] chat, notification 어드민 생성, 모델 __str__ 수정

---

apps/notification/consumers.py
apps/notification/serializers.py
apps/notification/tests.py
apps/notification/utils.py

- type을 시리얼라이저에서 내려주게 수정
- type 명칭을 수정하고 이에맞게 핸들러 함수 명도 변경
- 테스트 코드도 수정
- type을 시리얼라이저에서 내려주게 수정
- type 명칭을 수정하고 이에맞게 핸들러 함수 명도 변경
- 테스트 코드도 수정
- 
-

[Feature/notification] type을 시리얼라이저에서 내려주게 수정

---

.github/workflows/docker-cicd.yml
apps/category/tests.py
apps/category/views.py
apps/product/models.py
apps/product/serializers.py
apps/product/views.py
apps/user/tests.py

product 기능 보완
ProductViewSet
- filtering 항목 name 빼고 condition, size, region 추가
- ordering에 created_at, rental_fee, views 추가
ProductImage
- get_image_url 함수 구현해서 이미지 url 반환
ProductSerializer
- 요청으로 받은 이미지 중 기존 이미지는 링크로 들어오고 새 이미지는 파일로 들어와서 둘다 처리해줌
- 이미지 저장과 상품 정보 수정이 동시에 이루어지도록 트랜잭션으로 구현
category, user test code
- category 페이지네이션 제거해서 응답 데이터가 달라짐
- user 인증 설정 변경해서 user 테스트 코드에서 401 에러 발생
- 테스트 코드 다시 동작하도록 수정
- 
-

[Feature/image-transaction] 기존 이미지 링크 삭제되는 이슈 수정, user 테스트코드 수정, product 필터링, 정렬 항목 추가

---

apps/chat/admin.py
apps/chat/consumers.py
apps/chat/models.py
apps/chat/tests.py
apps/chat/utils.py
apps/notification/consumers.py
apps/notification/serializers.py
apps/notification/tests.py
apps/notification/utils.py

- confirm_notification: 기존에 모델을 받아서 인스턴스를 비교했는데 알 수 없는 이유로 동작하지않음 -> 커맨드를 받아서 알림읽음 동작
- product_image 키를 image 키로 변경
- Message 모델에서 timestamp를 삭제하고 BaseModel 상속
- 모델 변경에 따른 코드 수정
- 
-

[Feature/notification] 모델 변경에 따른 코드 수정, timestamp필드사용 대신 basemodel상속으로 변경

---

config/settings/local.py
config/settings/prod.py
config/urls.py
pyproject.toml

sentry 도입
- sentry 기본 설정만 추가
- sentry_sdk 설치
- 디스코드 채널 연결해서 알림 받기
- admin/ -> api/admin/으로 변경
- poetry install 필요
- 팀 초대하고 싶은데 유료인듯...
- 로컬에서 해보고 싶으면 가입해서 환경변수에 dsn만 바꿔서 넣고 local.py에 있는 설정 주석 해제하고 돌리면 됩니다.
- 성능이 떨어지면 rate 조절

[Feature/sentry] sentry 연결 설정

---

.gitignore
apps/like/admin.py
apps/like/apps.py
apps/like/models.py
apps/like/permissions.py
apps/like/serializers.py
apps/like/tests.py
apps/like/urls.py
apps/like/views.py
apps/product/models.py
apps/product/serializers.py
apps/user/tests.py
apps/user/urls.py
apps/user/views.py
config/settings/base.py
config/settings/local.py
config/urls.py
diagrams/like_diagram.md

좋아요 기능 구현
Like
- user, product UniqueConstraint로 구성
IsUserOrReadOnly
- 생성한 유저만 삭제 가능
LikeSerializer
- 목록 조회할 때는 product 정보가 모두 보이게 함
- 좋아요 생성할 때는 product_id만 보내게 함
TestLikeListCreateView
- 좋아요 목록 조회, 생성 기능 테스트코드 작성
TestLikeDestroyView
- 좋아요 취소 기능 테스트코드 작성
urls.py
- GET /api/likes/ 좋아요 목록 조회
- POST /api/likes/ 좋아요 생성
- DELETE /api/likes/{product_id} 좋아요 취소
LikeListCreateView
- get_queryset에서 요청한 유저로 필터링, 최신순으로 보여주기
- perform_create에서 좋아요 생성할때 Like 모델에 insert하고, Product 모델의 likes 값을 1 증가시키는 로직 트랜잭션으로 구현
LikeDestroyView
- get_object에서 쿼리 파라미터로 들어온 product_id로 Like 오브젝트 찾음
- perform_destroy에서 삭제하고, Product 모델의 likes 값을 1 감소시키는 로직 트랜잭션으로 구현
Product
- likes 필드 기본값 0으로 추가
ProductSerializer
- likes 필드 추가
user/tests.py
- 이미지 업로드 테스트 다시 주석 해제
like_diagram.md
- 좋아요 구현할때 방법이 여러가지 있는데 머리가 복잡해져서 한번 그려봄 …

[Feature/like] 상품 좋아요 기능 구현

---

apps/category/admin.py
apps/category/models.py
apps/category/serializers.py
apps/category/tests.py
apps/category/urls.py
apps/category/views.py
apps/mypage/admin.py
apps/mypage/apps.py
apps/mypage/models.py
apps/mypage/serializers.py
apps/mypage/tests.py
apps/mypage/urls.py
apps/mypage/views.py
apps/product/models.py
apps/product/serializers.py
apps/product/tests.py
apps/product/views.py
apps/user/models.py
apps/user/serializers.py
config/settings/base.py
config/settings/local.py
config/urls.py

내 상품 목록 조회, 상품에 스타일 태그 추가
MyProductSerializer
- 내가 등록한 상품을 모아서 조회할때 필요한 시리얼라이저
- ProductSerializer와 다른점은 lender와 is_like가 없음
MyProductListView
- 내가 등록한 상품 목록 조회 ListAPIView로 구현
MyProductTest
- test_get_my_products에서 내 상품 목록 조회 테스트
StyleAdmin
- 스타일 태그 등록할수 있도록 어드민 페이지 설정
Style
- 중복 제약 조건을 건 name 필드로 이루어진 모델
StyleSerializer
- 스타일 목록 조회에 필요한 시리얼라이저
StyleListView
- 스타일 목록 조회 가능한 뷰 ListAPIView로 구현
- 페이지네이션은 None으로 함
StyleListTest
- 스타일 목록 조회 테스트
Product
- styles 필드 ManyToManyField로 추가
ProductSerializer
- styles 필드 추가
- set_styles 함수를 만들어서 상품 등록, 수정할때 styles 추가할수 있도록 함
- is_liked 필드를 SerializerMethodField로 등록하고 get_is_liked에서 로그인한 유저가 상품에 좋아요 했는지 여부를 알려줌
base.py
- mypage 앱 등록
- category, product migrations 필요

[Feature/mypage] 내 상품 목록 조회, 상품에 스타일 태그 추가

---

apps/chat/views.py
apps/product/admin.py
apps/product/serializers.py
apps/product/tests.py
apps/product/urls.py
apps/product/views.py
tools/test_chat_locust.py

- serializers.py
- ProductInfoSerializer: 상품의 필요한 정보만 내려줌
- RentalHistorySerializer: 상품 추가, 조회, 수정을 위한 시리얼라이저
- 요청과 동일한 대여내역이 있으면 발리데이션 에러를 발생시킴
- 조회시 대여정보와 관련된 상품정보까지 같이 내려줌
- tests.py
- RentalHistoryTestBase: 테스트에 필요한 데이터들을 미리 셋업해두는 Base 클래스
- RentalHistoryBorrowerViewTests: 대여내역을 조회하고 대여신청을 테스트
- RentalHistoryLenderViewTests: 판매내역을 조회하는 테스트
- RentalHistoryUpdateViewTests: 대여상태를 업데이트하거나 반납연장 신청시 반납일을 업데이트 하는지 테스트
- urls.py
- api/products/rental_history/borrow: 대여 신청 및 조회
- api/products/rental_history/lending: 판매 내역 조회
- api/products/rental_history/<int:pk>/: 대여 상태 업데이트 및 반납일 연장
- views.py
- RentalHistoryBorrowerView: 대여 신청 및 대여 내역 조회, 대여신청 중복시 400
- RentalHistoryLenderView: 판매 내역 조회
- RentalHistoryUpdateView: 대여 상태 업데이트 및 반납일 수정
- 이미 나간방이 존재하더라도 새로운 채팅방 생성가능하도록 수정
- 버그 수정
- …

[Feature/rental] RentalHistory View 생성, 시리얼라이저 생성, 테스트코드 작성

---

apps/chat/tests.py
apps/chat/utils.py

[Fix/message-ordering] 채팅메시지 정렬순서 변경..

---

apps/chat/utils.py
apps/user/urls.py

[Fix/message ordering] 네이버 소셜로그인 url 추가

---

apps/chat/serializers.py
apps/chat/tests.py
apps/chat/utils.py
apps/chat/views.py
apps/product/views.py
apps/user/api_schema.py
apps/user/views.py

- user/views.py: OAuthLoginView.post에 request, response 스키마 추가
- chat/vies.py: 각 APIView클래스에 필요한 스키마 추가
- chat/utils.py: 기존에 mypy오류 때문에 따로 리스트에 담았던 ReturnDict를 list로 형변환만 해줌
- 스키마용 UserInfoSerializer 추가
- product_rental_fee: CharField -> IntegerField로 필드 수정
- 
-

[Inspection] drf-spectacluar 스키마 추가, 메시지 정렬 오류 수정, 테스트코드 수정

---

apps/chat/views.py

[inspection] 채팅방 만들기 오류 수정

---

apps/user/views.py

[inspection]소셜로그인시 csrf, 세션획득하는 부분 추가

---

apps/user/views.py

[inspection]mypy 수정, 파라미터 빼먹은거 수정..

---

apps/user/views.py

[inspection]소셜 로그인 시 user create 부분 수정

---

apps/user/views.py
config/settings/base.py

[Hotfix/inspection] csrf 쿠키 세팅 수정, 세션로그인 활성화

---

apps/chat/serializers.py
apps/chat/views.py
apps/product/serializers.py
apps/product/urls.py

[hotfix/inspection] 채팅방 입장시 상품에 대한 대여정보 내려주도록 변경

---

apps/product/serializers.py

[hotfix/inspection]RentalHistoryStatusSerializer에서 반납일, 대여일 내려주도록 수정

---

apps/chat/serializers.py
apps/chat/views.py
apps/product/models.py
apps/product/serializers.py
apps/product/tests.py
apps/product/views.py
apps/user/views.py

[Hotfix/inspection] 대여기록 생성 버그 수정, 테스트 코드 수정, 코드 포매터 적용
